version: '3'

services:
  apps:
    container_name: test_graphql_server-nextjs-auth-app-router
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3200:4300
    tty: true
    volumes:
      - type: bind
        source: ./nextjs-auth-app-router-sample
        target: /nextjs-auth-app-router-sample
    # environment:
    #   - WATCHPACK_POLLING=true


    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    #network_mode: 'host'
    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  # db:
  #   image: mysql:8.0
  #   container_name: mysql80-test_graphql_server-nextjs-prisma-graphql-codegen-proj
  #   restart: always
  #   env_file:
  #     - mysql.env
  #   ports:
  #     - 3313:3306
  #   volumes:
  #     - ./init_db:/docker-entrypoint-initdb.d
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: phpmyadmin-test_graphql_server-nextjs-prisma-graphql-codegen-proj
  #   restart: always
  #   depends_on:
  #     - db
  #   ports:
  #     - 9097:80
  #   volumes:
  #     - ./docker/phpmyadmin/sessions:/sessions
  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - 8025:8025
  #     - 1025:1025
  # volumes:
  #   mysql80vol-test_graphql_server-nextjs-prisma-graphql-codegen-proj:
  #     name: mysql80data-test_graphql_server-nextjs-prisma-graphql-codegen-proj
    
# volumes:
#   docker/db/data:
#   docker/db/my.cnf:
#   docker/db/sql:
# version: "3"

# services:
#   cli:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - 5002:5002
#     tty: true
#     volumes:
#       - type: bind
#         source: ./src
#         target: /src

# volumes:
#   bin:
#   out: